# Generated by Django 2.1.4 on 2019-02-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('_deleted', models.BooleanField(default=False, editable=False)),
                ('gender', models.CharField(choices=[('f', 'Femenino'), ('m', 'Masculino')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('document_number', models.BigIntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Aprovado'), (2, 'Rechazado')], default=0, editable=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
