# Generated by Django 2.1.4 on 2019-02-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestloan',
            name='amount',
            field=models.PositiveIntegerField(default=123, verbose_name='Monto a solicitar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestloan',
            name='full_name',
            field=models.CharField(default='Matias Roson', max_length=100, verbose_name='Nombre y apellido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestloan',
            name='document_number',
            field=models.BigIntegerField(verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='requestloan',
            name='gender',
            field=models.CharField(choices=[('f', 'Femenino'), ('m', 'Masculino')], max_length=1, verbose_name='Sexo'),
        ),
    ]
