# Generated by Django 2.1.4 on 2018-12-12 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiDummy',
        ),
    ]
